version: '3'
services:
  postgres_translate:
    image: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: translate_platform
    volumes:
      - postgres-translate-data:/var/lib/postgresql/data
    networks:
      - backend
    restart: always

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: simonesimone
    volumes:
    - mongodb-data:/data/db
    networks:
    - backend
    ports:
    - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 10.10.10.60:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: simonesimone
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: simonesimone
    depends_on:
    - mongodb
    networks:
    - backend
    ports:
    - 8081:8081
    healthcheck:
      test:  wget --quiet --tries=3 --spider http://admin:simonesimone@10.10.10.60:8081 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres_translate
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: simone@simone.it
      PGADMIN_DEFAULT_PASSWORD: simonesimone
    networks:
      - backend
    restart: unless-stopped

  frontend:
    build: ../frontend
    image: vue_app:0.0.1
    depends_on:
      - backend
    container_name: "vue_app_container"
    ports:
      - "80:80"
    networks:
      - frontend
    restart: always

  backend:
    build: ../backend
    image: express_app:0.0.1
    depends_on:
      - postgres
      - mongodb
    container_name: "express_app_container"
    ports:
      - "3000:3000"
    networks:
      - frontend
      - backend
    restart: always

volumes:
  postgres-translate-data:
  mongodb-data:

networks:
  frontend:
    name: custom_frontend
    driver: bridge
  backend:
    name: custom_backend
    driver: bridge
