version: '3'
services:
  postgres_translate:
    image: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: translate_platform
    volumes:
      - postgres-translate-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres_translate
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: simone@simone.it
      PGADMIN_DEFAULT_PASSWORD: simonesimone
    restart: unless-stopped

volumes:
  postgres-translate-data:
